const states = {
  states_us: [
    { value: 'AL', text: 'Alabama' },
    { value: 'AK', text: 'Alaska' },
    { value: 'AZ', text: 'Arizona' },
    { value: 'AR', text: 'Arkansas' },
    { value: 'CA', text: 'California' },
    { value: 'CO', text: 'Colorado' },
    { value: 'CT', text: 'Connecticut' },
    { value: 'DE', text: 'Delaware' },
    { value: 'DC', text: 'District Of Columbia' },
    { value: 'FL', text: 'Florida' },
    { value: 'GA', text: 'Georgia' },
    { value: 'HI', text: 'Hawaii' },
    { value: 'ID', text: 'Idaho' },
    { value: 'IL', text: 'Illinois' },
    { value: 'IN', text: 'Indiana' },
    { value: 'IA', text: 'Iowa' },
    { value: 'KS', text: 'Kansas' },
    { value: 'KY', text: 'Kentucky' },
    { value: 'LA', text: 'Louisiana' },
    { value: 'ME', text: 'Maine' },
    { value: 'MD', text: 'Maryland' },
    { value: 'MA', text: 'Massachusetts' },
    { value: 'MI', text: 'Michigan' },
    { value: 'MN', text: 'Minnesota' },
    { value: 'MS', text: 'Mississippi' },
    { value: 'MO', text: 'Missouri' },
    { value: 'MT', text: 'Montana' },
    { value: 'NE', text: 'Nebraska' },
    { value: 'NV', text: 'Nevada' },
    { value: 'NH', text: 'New Hampshire' },
    { value: 'NJ', text: 'New Jersey' },
    { value: 'NM', text: 'New Mexico' },
    { value: 'NY', text: 'New York' },
    { value: 'NC', text: 'North Carolina' },
    { value: 'ND', text: 'North Dakota' },
    { value: 'OH', text: 'Ohio' },
    { value: 'OK', text: 'Oklahoma' },
    { value: 'OR', text: 'Oregon' },
    { value: 'PA', text: 'Pennsylvania' },
    { value: 'RI', text: 'Rhode Island' },
    { value: 'SC', text: 'South Carolina' },
    { value: 'SD', text: 'South Dakota' },
    { value: 'TN', text: 'Tennessee' },
    { value: 'TX', text: 'Texas' },
    { value: 'UT', text: 'Utah' },
    { value: 'VT', text: 'Vermont' },
    { value: 'VA', text: 'Virginia' },
    { value: 'WA', text: 'Washington' },
    { value: 'WV', text: 'West Virginia' },
    { value: 'WI', text: 'Wisconsin' },
    { value: 'WY', text: 'Wyoming' },
    { value: 'AS', text: 'American Samoa' },
    { value: 'GU', text: 'Guam' },
    { value: 'MP', text: 'Northern Mariana Islands' },
    { value: 'PR', text: 'Puerto Rico' },
    { value: 'UM', text: 'United States Minor Outlying Islands' },
    { value: 'VI', text: 'Virgin Islands' },
  ],
  states_mx: [
    { value: 'DIF', text: 'Distrito Federal' },
    { value: 'AGS', text: 'Aguascalientes' },
    { value: 'BCN', text: 'Baja California' },
    { value: 'BCS', text: 'Baja California Sur' },
    { value: 'CAM', text: 'Campeche' },
    { value: 'CHP', text: 'Chiapas' },
    { value: 'CHI', text: 'Chihuahua' },
    { value: 'COA', text: 'Coahuila' },
    { value: 'COL', text: 'Colima' },
    { value: 'DUR', text: 'Durango' },
    { value: 'GTO', text: 'Guanajuato' },
    { value: 'GRO', text: 'Guerrero' },
    { value: 'HGO', text: 'Hidalgo' },
    { value: 'JAL', text: 'Jalisco' },
    { value: 'MEX', text: 'M&eacute;xico' },
    { value: 'MIC', text: 'Michoac&aacute;n' },
    { value: 'MOR', text: 'Morelos' },
    { value: 'NAY', text: 'Nayarit' },
    { value: 'NLE', text: 'Nuevo Le&oacute;n' },
    { value: 'OAX', text: 'Oaxaca' },
    { value: 'PUE', text: 'Puebla' },
    { value: 'QRO', text: 'Quer&eacute;taro' },
    { value: 'ROO', text: 'Quintana Roo' },
    { value: 'SLP', text: 'San Luis Potos&iacute;' },
    { value: 'SIN', text: 'Sinaloa' },
    { value: 'SON', text: 'Sonora' },
    { value: 'TAB', text: 'Tabasco' },
    { value: 'TAM', text: 'Tamaulipas' },
    { value: 'TLX', text: 'Tlaxcala' },
    { value: 'VER', text: 'Veracruz' },
    { value: 'YUC', text: 'Yucat&aacute;n' },
    { value: 'ZAC', text: 'Zacatecas' },
  ],
  provinces_ca: [
    { value: 'AB', text: 'Alberta' },
    { value: 'BC', text: 'British Columbia' },
    { value: 'MB', text: 'Manitoba' },
    { value: 'NB', text: 'New Brunswick' },
    { value: 'NL', text: 'Newfoundland and Labrador' },
    { value: 'NS', text: 'Nova Scotia' },
    { value: 'ON', text: 'Ontario' },
    { value: 'PE', text: 'Prince Edward Island' },
    { value: 'QC', text: 'Quebec' },
    { value: 'SK', text: 'Saskatchewan' },
    { value: 'NT', text: 'Northwest Territories' },
    { value: 'NU', text: 'Nunavut' },
    { value: 'YT', text: 'Yukon' },
  ]
};

export default states;
