/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:df34f322-a2f9-4c34-9f0b-54cdcac02610",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_3EBw6uUX2",
    "aws_user_pools_web_client_id": "6va9mhndec3rfsd4t9mv0g9rvq",
    "oauth": {
        "domain": "validate-registration.auth.us-west-2.amazoncognito.com"
    },
    "aws_cognito_login_mechanisms": [
        "PREFERRED_USERNAME"
    ],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_types": [],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [],
    "aws_appsync_graphqlEndpoint": "https://el45zb6obrdrhkjrag6nqdvdk4.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "form-content33808-feat",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
