/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:df34f322-a2f9-4c34-9f0b-54cdcac02610",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_3EBw6uUX2",
    "aws_user_pools_web_client_id": "6va9mhndec3rfsd4t9mv0g9rvq",
    "oauth": {
        "domain": "validate-registration.auth.us-west-2.amazoncognito.com"
    },
    "aws_appsync_graphqlEndpoint": "https://uyc7wn573rg7vl47o74vwr2ieu.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
